create table if not exists public.slot_scores (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  name text not null,
  score integer not null,
  credits integer not null,
  last_win integer not null default 0
);

alter table public.slot_scores enable row level security;

drop policy if exists "Public can read slot scores" on public.slot_scores;
create policy "Public can read slot scores"
on public.slot_scores
for select
to anon
using (true);

drop policy if exists "Public can insert slot scores" on public.slot_scores;
create policy "Public can insert slot scores"
on public.slot_scores
for insert
to anon
with check (
  char_length(name) between 1 and 18
  and score between 0 and 100000000
  and credits between 0 and 100000000
  and last_win between 0 and 100000000
);
